### ISSUE TITLE
Any plans to do cross-platform edition (version) of your cool Trippit app?

### ISSUE THREAD

**Issue by mediaexplorer74** [pingzing/digi-transit-10#53]
Hello, Neil aka [pingzing](https://github.com/pingzing)! 

I found your great UWP app for some own "win10mobile dev experiments" :) You are cool/great UI C# developer / designer, indeed!
I want to ask you about history and future plans of this nice app . 
Did/do you plan to do cross-platform edition (version) using Xamarin Forms or Uno? =)

Or maybe are you big fanboy of Finnish Lumia phones (in past) ? ;) I'll be glad to see W10M ARM32 version of Trippit app with some compact UI... :)  I still using (sometimes) my Microsoft-Nokia Lumia 950 for photography deals, etc. :)  And... in my 48-year old life I never visit Finland country, heh .

Best / cheers up,
M.E.

**Comment by pingzing** [comment]
Oh, wow, hello. I didn't think anybody even knew about this old thing. Thank you for your comments!

This app was originally written _for_ my Windows 10 Mobile phone--I was annoyed that the only apps that supported my shiny new Lumia 950 were old WP8.1 apps that didn't take advantage of the (at the time) shiny new features in Windows 10. And I figured, hey, I also get a desktop app out of it. Win-win! (I can see that you got it compiling for W10M in your other issue. Good stuff.)

Then, Windows Mobile abruptly died, and with it, so did all my motivation to work on this thing. Ah, well.

No plans to port it over to a newer, better-supported framework. I think about it every now and then, but it would be a lot of work (that i don't really have time for these days), and there are better apps on the target platforms already. If I _did_ do it, I'd probably use Avalonia, once its mobile support is a bit more mature.
