### ISSUE TITLE
The role of Windows Desktop Extensions for UWP

### ISSUE THREAD

**Issue by mediaexplorer74** [pingzing/digi-transit-10#54]
I have the/an issue about the role of Windows Desktop Extensions for UWP.
I noticed that you added only Windows Mobile Extensions for UWP (in)to your cool Trippit project. It's ok? I got some strange Geolocation service exception when I tried to start untouched src codes... Maybe, there are some problem my Windows 11 Tiny or 11-year old Sony Vaio ... idk :) But when I added Windows Desktop Extensions for UWP then all seem to be normal/ok :
![image](https://github.com/pingzing/trippit/assets/12032735/7e0e5663-ecd3-4f64-819f-73c9402633df)
![image](https://github.com/pingzing/trippit/assets/12032735/d7096145-0352-4373-bcc8-84c242010bbc)
![image](https://github.com/pingzing/trippit/assets/12032735/abb03246-cc18-4cf3-8880-21f938605872)

P.S. I'm sucessfully changed Min. os. SDK build to 15063. Your great code compiled sucessful(ly). I'm "shocked" , it's W10M-compatible! Magic, indeed...

**Comment by pingzing** [comment]
It's been long enough, that I don't really remember anymore. I have an extremely vague recollection that I needed the Mobile extensions to... access the phone system tray, I think? Maybe also for something to do with toast notifications?

No idea what the Geolocation exception might be. I guess that could also be part of the Extensions SDK.
